### ISSUE TITLE
Gap in the upper left?

### ISSUE THREAD

**Issue by nickom** [sunlightlabs/sotumachine#15]
Not sure if this has to do with the branding bar, but I'm seeing it all browsers:
![screen shot 2015-01-14 at 5 50 26 pm](https://cloud.githubusercontent.com/assets/3171982/5749325/fc095e18-9c15-11e4-8d37-11528dc1c9d4.png)

**Comment by boblannon** [comment]
looks like this might be because i haven't updated sfapp. more info soon

**Comment by boblannon** [comment]
(fixed by sunlightlabs/sfapp@3a5a64b3)
