### ISSUE TITLE
add more description to top

### ISSUE THREAD

**Issue by stereogab** [sunlightlabs/sotumachine#20]
Please change from 

Generate a random State of the Union based on language modeling of the speeches from previous presidents. Learn more about the nonpartisan Sunlight Foundation and our tools here. Highlight your favorite quotes to share!

to

Generate a random State of the Union based on language modeling of the speeches from previous presidents by using the sliders on the left. SOTU Machine now includes last year's address and text from recent speeches by President Obama that the White House calls a "spoiler alert." Use the "Obama's Pre-SOTU Tour" lever to predict what might the president might say this time. After selecting a mix of the speeches, highlight your favorite quote found in the generated text and share it by clicking on the Twitter icon using #SOTUMachine. Highlight your favorite quotes to share!  Learn more about the nonpartisan Sunlight Foundation and our tools here.

**Comment by heyitsolivia** [comment]
This is a lot of dense text that I don't think a lot of people will read. Do we really need the step-by-step instructions for how to use the UI?

If anything I could see the explanation for the "Pre-SOTU Tour" added in as a tooltip next to the slider.
