### ISSUE TITLE
Rotate president rollover text with the outside of the bubble

### ISSUE THREAD

**Issue by nickom** [sunlightlabs/sotumachine#5]
The left and upper left selections cause the name to appear over the image.

![screen shot 2014-01-27 at 11 15 42 am](https://f.cloud.github.com/assets/3171982/2010479/6df30014-876e-11e3-8a17-fd4bd9fe875c.png)

![screen shot 2014-01-27 at 11 15 47 am](https://f.cloud.github.com/assets/3171982/2010480/6ffa153c-876e-11e3-95f4-7e77c47296f7.png)

**Comment by nickom** [comment]
This still happens
cc @heyitsolivia

**Comment by heyitsolivia** [comment]
1ee003c16b9efbf411c701ac97178df2edac14a3 replaces the tooltip with a label and gets rid of this problem

**Comment by boblannon** [comment]
word.
