### ISSUE TITLE
Random backticks in text

### ISSUE THREAD

**Issue by nickom** [sunlightlabs/sotumachine#8]
Bob knows about this, but thought I would make an issue in case others have a fix in mind...

![screen shot 2014-01-27 at 11 42 08 am](https://f.cloud.github.com/assets/3171982/2010777/12727478-8772-11e3-9aef-1ffeb91cf33d.png)

**Comment by nickom** [comment]
This doesn't seem to be happening anymore - close @boblannon ?

**Comment by boblannon** [comment]
no, it's still happening. I'll see what i can do about it.
