### ISSUE TITLE
Scrolling while showing wheel rollover causes text to scroll

### ISSUE THREAD

**Issue by nickom** [sunlightlabs/sotumachine#9]
Two examples:

![scroll-ruins-rollover](https://f.cloud.github.com/assets/3171982/2011412/8d665156-877a-11e3-97cb-9d946e0fea67.gif)

![scroll-ruins-rollover2](https://f.cloud.github.com/assets/3171982/2011415/8fedff00-877a-11e3-9920-258d3abf4d15.gif)

**Comment by nickom** [comment]
This still happens and is still super minor.

**Comment by heyitsolivia** [comment]
I think this is intentional for tooltips on highlighted speech text, and 1ee003c16b9efbf411c701ac97178df2edac14a3 removes tooltips from the donut chart.

**Comment by boblannon** [comment]
that's great, and looks really sharp!
